### ISSUE TITLE
BUG: assertSmallDatasetEquality highlights wrong schema mismatch when ignoreNullable = true

### ISSUE THREAD

**Issue by crazylab** [mrpowers-io/spark-fast-tests#101]
**How to Reproduce**:
```scala
import spark.implicits._
val df1 = Seq((1, Some(5))).toDF("c1", "c2")
val df2 = Seq(("abc", 5)).toDF("c1", "c2")

assertSmallDatasetEquality(df1, df2, ignoreNullable = true)
```

**What is wrong:**
In the above case, ideally, schema mismatch should highlight column `c1` only.
Column `c2` is nullable. As I have set `ignoreNullable = true` it should not be highlighted in schema mismatch.

![Screenshot 2021-11-28 at 1 55 54 PM](https://user-images.githubusercontent.com/83529842/143735191-5e5a659e-91d6-40bf-9553-7685b5b61c17.png)

**Expected Behaviour:**
`assertSmallDatasetEquality(df1, df2, ignoreNullable = true)` should only highlight schema mismatch for column `c1`.

**Comment by nchammas** [comment]
What version of spark-fast-tests did you test this with?
