### ISSUE TITLE
Adding Contributor Proposal

### ISSUE THREAD

**Issue by zeotuan** [mrpowers-io/spark-fast-tests#121]
Hi @MrPowers,

I wanted to take a moment to discuss the current status of our repository and explore opportunities to revitalize its activity. I've noticed that the repository has not been updated since 2022, unlike its Python counterpart (Chispa). While Python is much more commonly used, this project is very essential for many Scala Spark projects.

Are you open to the idea of adding potential active contributors to the repository? Ideally, this would allow us to:
- Ensure spark-fast-tests has releases to support newer Spark versions, which is crucial.
- Maintain API or feature compatibility between Chispa and spark-fast-tests (or perhaps create a whole new project from this).
- Implement bug fixes, performance improvements, and new features.

Another alternative is to create and announce an official fork and start directing interested maintainers to it, but I want to avoid this scenario.

For starters, I would like to volunteer myself.

Let me know your thoughts!

**Comment by SemyonSinchenko** [comment]
@zeotuan Hi! We discussed it with @MrPowers. As you may see the project was migrated to `mrpowers-io`. I and @alfonsorr commited to maintain it. At the moment I'm trying to revisit an open issues.

I see that the following as next steps:
- Add tests against latest spark versions (3.3, 3.4, 3.5);
- Maybe drop tests against 2.x.x
- Update the documentation (issues template, contributing, etc.)
- Prepare a new release that supports 3.3, 3.4, 3.5
