### ISSUE TITLE
[Performance Improvement] default to row equal implementation if tolerance is 0

### ISSUE THREAD

**Issue by zeotuan** [mrpowers-io/spark-fast-tests#124]
using default `equals` implementation from Row should be much more performance. We can improve Dataframe equality assertion speed if strict comparison is required.

**Comment by SemyonSinchenko** [comment]
@zeotuan At the moment strict equality is [checked first](https://github.com/mrpowers-io/spark-fast-tests/blob/main/src/main/scala/com/github/mrpowers/spark/fast/tests/DatasetComparer.scala#L182) using `Row.equals`.
