### ISSUE TITLE
assertSmallDataFrameEquality on DataFrames with StructType columns

### ISSUE THREAD

**Issue by MrPowers** [mrpowers-io/spark-fast-tests#37]
`assertSmallDataFrameEquality` doesn't work on DataFrames with StructType columns as illustrated in this PR: https://github.com/MrPowers/spark-fast-tests/pull/36

Need to fix this bug... not sure how yet.  Possibly will use `flattenSchema` and then do the comparison.

**Comment by awhillas** [comment]
I don't know if this is related but `assertSmallDataFrameEquality` seems give me a weird error:

> java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: **java.lang.Integer is not a valid external type for schema of bigint**
validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, pressroom_id), IntegerType) AS pressroom_id#31
validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, year), IntegerType) AS year#32
validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 2, month), IntegerType) AS month#33
validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 3, total_content), LongType) AS total_content#34L

and here is the test I'm doing
```scala
 it("Engagment total_content works") {

    val sourceDF = spark.createDF(
      List(
        // PR 1 should have 1 in Dec. and 2 in Nov.
        (1, Timestamp.valueOf("2017-12-02 03:04:00"), "1-123"),
        (1, Timestamp.valueOf("2017-11-01 00:04:00"), "2-133"),
        (1, Timestamp.valueOf("2017-11-02 00:04:00"), "2-134"),
        // PR 2 should have 2 in Nov.
        (2, Timestamp.valueOf("2017-11-11 00:04:00"), "3-133"),
        (2, Timestamp.valueOf("2017-11-22 00:04:00"), "4-133"),
        (3, Timestamp.valueOf("2017-11-22 00:04:00"), "4-143")
      ), List (
        ("pressroom_id", IntegerType, false),
        ("published_at", TimestampType,  false),
        ("gcid", StringType, false)
      )
    )

    val actualDF = sourceDF.transform(Engagement.process)
    
    val expectedDF = spark.createDF(
      List(
        (1, 2017, 12, 1),
        (1, 2017, 11, 2),
        (2, 2017, 11, 2),
        (3, 2017, 11, 1)
      ), List (
        StructField("pressroom_id", IntegerType, false),
        StructField("year", IntegerType, false),
        StructField("month", IntegerType, false),        
        StructField("total_content", LongType, false)
      )
    )

    assertSmallDataFrameEquality(actualDF, expectedDF)
  }
```
Is this related?

**Comment by MrPowers** [comment]
@awhillas - I don't think your issue is related, but this should solve your issue:

```scala
    val expectedDF = spark.createDF(
      List(
        (1, 2017, 12, 1),
        (1, 2017, 11, 2),
        (2, 2017, 11, 2),
        (3, 2017, 11, 1)
      ), List (
        StructField("pressroom_id", IntegerType, false),
        StructField("year", IntegerType, false),
        StructField("month", IntegerType, false),        
        StructField("total_content", LongType, false)
      )
    )
```

**Comment by awhillas** [comment]
It did thanks! *embarrassed*

**Comment by zeotuan** [comment]
I am going to close this issue as it has already been supported! Feel free to open if you find any issue.
